## Deliverable 3. Create a Travel Itinerary Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [2]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("../Vacation_Search/WeatherPy_vacation.csv")
vacation_df.head()

City_ID             City Country  Max Temp Current Description      Lat  \
0        0            Vaini      TO     71.76     overcast clouds -21.2000   
1        2            Tabou      CI     78.03          light rain   4.4230   
2        5  Arraial Do Cabo      BR     66.16                mist -22.9661   
3        6           Avarua      CK     75.25     overcast clouds -21.2078   
4        7   Saint-Philippe      RE     72.95          few clouds -21.3585   

        Lng                    Hotel Name  
0 -175.2000           Keleti Beach Resort  
1   -7.3528            hotêl doufoulougou  
2  -42.0278           Pousada Porto Praia  
3 -159.7750                  Paradise Inn  
4   55.7679  Chambres d'hôte "La Trinité"

In [3]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Description</dt><dd>Current Description</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [4]:
# 4a. Add a marker layer for each city to the map.
locations = vacation_df[["Lat", "Lng"]]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)
# 4b. Display the figure
fig


Figure(layout=FigureLayout(height='420px'))

In [38]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start = vacation_df.loc[(vacation_df['City'] == 'Ukiah')]
vacation_end = vacation_df.loc[(vacation_df['City'] == 'Ukiah')]
vacation_stop1 = vacation_df.loc[(vacation_df['City'] == 'Laguna')]
vacation_stop2 = vacation_df.loc[(vacation_df['City'] == 'San Joaquin')] 
vacation_stop3 = vacation_df.loc[(vacation_df['City'] == 'Half Moon Bay')] 

In [39]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = vacation_start[["Lat", "Lng"]].to_numpy()
print(start)
end = vacation_end[["Lat", "Lng"]].to_numpy()
print(end)
stop1 = vacation_stop1[["Lat", "Lng"]].to_numpy()
print(stop1)
stop2 = vacation_stop2[["Lat", "Lng"]].to_numpy()
print(stop2)
stop3 = vacation_stop3[["Lat", "Lng"]].to_numpy()
print(stop3)

[[  39.1502 -123.2078]]
[[  39.1502 -123.2078]]
[[  38.421  -121.4238]]
[[  37.9333 -121.3011]]
[[  37.4636 -122.4286]]


In [7]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".
fig = gmaps.figure()
start = start[0]
end = end[0]
waypoints = [stop1[0], stop2[0], stop3[0]]
directions = gmaps.directions_layer(start, end, waypoints=waypoints, travel_mode='DRIVING')
fig.add_layer(directions)
fig


Figure(layout=FigureLayout(height='420px'))

In [40]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start, vacation_stop1, vacation_stop2, vacation_stop3],ignore_index=True)
itinerary_df

City_ID           City Country  Max Temp Current Description      Lat  \
0      443          Ukiah      US     81.12           clear sky  39.1502   
1      170         Laguna      US     78.89           clear sky  38.4210   
2      140    San Joaquin      US     78.94           clear sky  37.9333   
3      196  Half Moon Bay      US     80.58           clear sky  37.4636   

        Lng                                         Hotel Name  
0 -123.2078                                  Hampton Inn Ukiah  
1 -121.4238  Holiday Inn Express & Suites Elk Grove Central...  
2 -121.3011                  University Plaza Waterfront Hotel  
3 -122.4286                    The Ritz-Carlton, Half Moon Bay

In [41]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dl>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Description</dt><dd>Current Description</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [43]:
# 11a. Add a marker layer for each city to the map.
fig = gmaps.figure()

marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))